### ISSUE TITLE
Improve ELO-rating calculation

### ISSUE THREAD

**Issue by ertkjern** [ertkjern/fuss-rating#4]
**The calculation of the rating after each match can be optimised and better.** 

The function for calculating the ELO-rating can be found in the `matchmaker.service.ts` named `calculateELORating ` : https://github.com/ertkjern/fuss-rating/blob/master/src/app/shared/services/matchmaker.service.ts

The function has two parameters. The first param: `player1Won` tells if player1 won or lost the game. 
The second parameter `match` is the MatchModel. It contains all the information about the match. The only thing we need here tough is the `match.player1.rating;` and `match.player2.rating;`.

In the end of the function the `match.player1.rating;` and `match.player2.rating;` is updated in the match model, and the data is stored to the database.

**Comment by lukarim** [comment]
The factor K=32 should be lower, as the ratings fluctuate too much for the initial value of 1500. Perhaps 16 or 20 would be more appropriate values, 24 at most. 
I believe that in the chess ratings the factor is 30 for the first 30 games, 20 after that, and 10 as soon as the player crosses 2400 (until death :)). In order to implement this, one would need to assign a factor to each player and follow the number of games played by that player.

**Comment by ertkjern** [comment]
K=20 now

**Comment by ertkjern** [comment]
Thanks for help and feedback @lukarim <3
